deploy:
  kmesh:
    env:
      bpfLogSize: "12800"
      meshController: istiod.istio-system.svc:15012
    image:
      repository: ghcr.io/kmesh-net/kmesh
      tag: local
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: 800Mi
kubernetesClusterDomain: cluster.local
